module.exports = {
	MODEL: 'VR-120HD',
	VERSION: '',
	TALLYDATA: [
		{ id: 0, label: 'HDMI 1', shortlabel: 'hdmi1', status: 0},
		{ id: 1, label: 'HDMI 2', shortlabel: 'hdmi2', status: 0},
		{ id: 2, label: 'HDMI 3', shortlabel: 'hdmi3', status: 0},
		{ id: 3, label: 'HDMI 4', shortlabel: 'hdmi4', status: 0},
		{ id: 4, label: 'HDMI 5', shortlabel: 'hdmi5', status: 0},
		{ id: 5, label: 'HDMI 6', shortlabel: 'hdmi6', status: 0},
		{ id: 6, label: 'HDMI 7', shortlabel: 'hdmi7', status: 0},
		{ id: 7, label: 'HDMI 8', shortlabel: 'hdmi8', status: 0},
		{ id: 8, label: 'SDI 1',  shortlabel: 'sdi1',  status: 0},
		{ id: 9, label: 'SDI 2',  shortlabel: 'sdi2',  status: 0},
		{ id: 10, label: 'SDI 3', shortlabel: 'sdi3',  status: 0},
		{ id: 11, label: 'SDI 4', shortlabel: 'sdi4',  status: 0},
		{ id: 12, label: 'SDI 5', shortlabel: 'sdi5',  status: 0},
		{ id: 13, label: 'SDI 6', shortlabel: 'sdi6',  status: 0},
		{ id: 14, label: 'SDI 7', shortlabel: 'sdi7',  status: 0},
		{ id: 15, label: 'SDI 8', shortlabel: 'sdi8',  status: 0},
		{ id: 16, label: 'STILL 1', shortlabel: 'still1',  status: 0},
		{ id: 17, label: 'STILL 2', shortlabel: 'still2',  status: 0},
		{ id: 18, label: 'STILL 3', shortlabel: 'still3',  status: 0},
		{ id: 19, label: 'STILL 4', shortlabel: 'still4',  status: 0},
		{ id: 20, label: 'STILL 5', shortlabel: 'still5',  status: 0},
		{ id: 21, label: 'STILL 6', shortlabel: 'still6',  status: 0},
		{ id: 22, label: 'STILL 7', shortlabel: 'still7',  status: 0},
		{ id: 23, label: 'STILL 8', shortlabel: 'still8',  status: 0},
		{ id: 24, label: 'STILL 9', shortlabel: 'still9',  status: 0},
		{ id: 25, label: 'STILL 10', shortlabel: 'still10',  status: 0},
		{ id: 26, label: 'STILL 11', shortlabel: 'still11',  status: 0},
		{ id: 27, label: 'STILL 12', shortlabel: 'still12',  status: 0},
		{ id: 28, label: 'STILL 13', shortlabel: 'still13',  status: 0},
		{ id: 29, label: 'STILL 14', shortlabel: 'still14',  status: 0},
		{ id: 30, label: 'STILL 15', shortlabel: 'still15',  status: 0},
		{ id: 31, label: 'STILL 16', shortlabel: 'still16',  status: 0},
		{ id: 32, label: 'XPT 1', shortlabel: 'xpt1',  status: 0},
		{ id: 33, label: 'XPT 2', shortlabel: 'xpt2',  status: 0},
		{ id: 34, label: 'XPT 3', shortlabel: 'xpt3',  status: 0},
		{ id: 35, label: 'XPT 4', shortlabel: 'xpt4',  status: 0},
		{ id: 36, label: 'XPT 5', shortlabel: 'xpt5',  status: 0},
		{ id: 37, label: 'XPT 6', shortlabel: 'xpt6',  status: 0},
		{ id: 38, label: 'XPT 7', shortlabel: 'xpt7',  status: 0},
		{ id: 39, label: 'XPT 8', shortlabel: 'xpt8',  status: 0},
		{ id: 40, label: 'XPT 9', shortlabel: 'xpt9',  status: 0},
		{ id: 41, label: 'XPT 10', shortlabel: 'xpt10',  status: 0}
	],

	CHOICES_INPUTS: [
		{ id: 0, label: 'Input 1' },
		{ id: 1, label: 'Input 2' },
		{ id: 2, label: 'Input 3' },
		{ id: 3, label: 'Input 4' },
		{ id: 4, label: 'Input 5' },
		{ id: 5, label: 'Input 6' },
		{ id: 6, label: 'Input 7' },
		{ id: 7, label: 'Input 8' },
	],

	CHOICES_INPUTSASSIGN: [
		{ id: 0, label: 'HDMI 1' },
		{ id: 1, label: 'HDMI 2' },
		{ id: 2, label: 'HDMI 3' },
		{ id: 3, label: 'HDMI 4' },
		{ id: 4, label: 'HDMI 5' },
		{ id: 5, label: 'HDMI 6' },
		
		{ id: 6, label: 'SDI 1' },
		{ id: 7, label: 'SDI 2' },
		{ id: 8, label: 'SDI 3' },
		{ id: 9, label: 'SDI 4' },
		{ id: 10, label: 'SDI 5' },
		{ id: 11, label: 'SDI 6' },

		{ id: 12, label: 'Still 1' },
		{ id: 13, label: 'Still 2' },
		{ id: 14, label: 'Still 3' },
		{ id: 15, label: 'Still 4' },
		{ id: 16, label: 'Still 5' },
		{ id: 17, label: 'Still 6' },
		{ id: 18, label: 'Still 7' },
		{ id: 19, label: 'Still 8' },
		{ id: 20, label: 'Still 9' },
		{ id: 21, label: 'Still 10' },
		{ id: 22, label: 'Still 11' },
		{ id: 23, label: 'Still 12' },
		{ id: 24, label: 'Still 13' },
		{ id: 25, label: 'Still 14' },
		{ id: 26, label: 'Still 15' },
		{ id: 27, label: 'Still 16' },

		{ id: 28, label: 'Video Player' },
		{ id: 29, label: 'Stream/Record Status 1' },
		{ id: 30, label: 'Stream/Record Status 2' },
		{ id: 31, label: 'Date & Time' },
	],

	CHOICES_INPUTSAUXASSIGN: [
		{ id: 0, label: 'HDMI 1' },
		{ id: 1, label: 'HDMI 2' },
		{ id: 2, label: 'HDMI 3' },
		{ id: 3, label: 'HDMI 4' },
		{ id: 4, label: 'HDMI 5' },
		{ id: 5, label: 'HDMI 6' },
		
		{ id: 6, label: 'SDI 1' },
		{ id: 7, label: 'SDI 2' },
		{ id: 8, label: 'SDI 3' },
		{ id: 9, label: 'SDI 4' },
		{ id: 10, label: 'SDI 5' },
		{ id: 11, label: 'SDI 6' },

		{ id: 12, label: 'Still 1' },
		{ id: 13, label: 'Still 2' },
		{ id: 14, label: 'Still 3' },
		{ id: 15, label: 'Still 4' },
		{ id: 16, label: 'Still 5' },
		{ id: 17, label: 'Still 6' },
		{ id: 18, label: 'Still 7' },
		{ id: 19, label: 'Still 8' },
		{ id: 20, label: 'Still 9' },
		{ id: 21, label: 'Still 10' },
		{ id: 22, label: 'Still 11' },
		{ id: 23, label: 'Still 12' },
		{ id: 24, label: 'Still 13' },
		{ id: 25, label: 'Still 14' },
		{ id: 26, label: 'Still 15' },
		{ id: 27, label: 'Still 16' },

		{ id: 28, label: 'Video Player' },

		{ id: 29, label: 'Input 1' },
		{ id: 30, label: 'Input 2' },
		{ id: 31, label: 'Input 3' },
		{ id: 32, label: 'Input 4' },
		{ id: 33, label: 'Input 5' },
		{ id: 34, label: 'Input 6' },
		{ id: 35, label: 'Input 7' },
		{ id: 36, label: 'Input 8' },
	],

	CHOICES_OUTPUTS: [
		{ id: 8,  label: 'HDMI Output 1' },
		{ id: 9,  label: 'HDMI Output 2' },
		{ id: 10, label: 'HDMI Output 3' },
		{ id: 11, label: 'SDI Output 1' },
		{ id: 12, label: 'SDI Output 2' },
		{ id: 13, label: 'SDI Output 3' },
		{ id: 14, label: 'USB Output' },
		{ id: 15, label: 'Stream/Record' },
		{ id: 16, label: 'LCD Monitor' },
	],

	CHOICES_OUTPUTSASSIGN: [
		{ id: 0, label: 'Program' },
		{ id: 1, label: 'Sub Program' },
		{ id: 2, label: 'Preview' },
		{ id: 3, label: 'Aux' },
		{ id: 4, label: 'Multi-View' },
		{ id: 5, label: 'Input-View' },
		{ id: 6, label: 'Still-View' },
	],

	CHOICES_PINPDSK: [
		{ id: 18, label: 'Program Layer PinP & Key 1' },
		{ id: 19, label: 'Program Layer PinP & Key 2' },
		{ id: 20, label: 'Program Layer PinP & Key 3' },
		{ id: 21, label: 'Program Layer PinP & Key 4' },
		{ id: 22, label: 'Program Layer DSK 1' },
		{ id: 23, label: 'Program Layer DSK 2' },
		{ id: 24, label: 'Sub Program Layer PinP & Key 1' },
		{ id: 25, label: 'Sub Program Layer PinP & Key 2' },
		{ id: 26, label: 'Sub Program Layer PinP & Key 3' },
		{ id: 27, label: 'Sub Program Layer PinP & Key 4' },
		{ id: 28, label: 'Sub Program Layer DSK 1' },
		{ id: 29, label: 'Sub Program Layer DSK 2' }
	],

	CHOICES_TRANSITION_TYPES: [
		{ id: 0, label: 'Mix' },
		{ id: 1, label: 'Wipe' },
		{ id: 2, label: 'Split 1' },
		{ id: 3, label: 'Split 2' }
	],

	CHOICES_MIX_TYPES: [
		{ id: 0, label: 'Mix' },
		{ id: 1, label: 'Fam' },
		{ id: 2, label: 'Nam' }
	],

	CHOICES_WIPE_TYPES: [
		{ id: 0, label: 'Horizontal' },
		{ id: 1, label: 'Vertical' },
		{ id: 2, label: 'Upper Left' },
		{ id: 3, label: 'Upper Right' },
		{ id: 4, label: 'Lower Left' },
		{ id: 5, label: 'Lower Right' },
		{ id: 6, label: 'H-Center' },
		{ id: 7, label: 'V-Center' }
	],

	CHOICES_WIPE_DIRECTIONS: [
		{ id: 0, label: 'Normal' },
		{ id: 1, label: 'Reverse' },
		{ id: 2, label: 'Round Trip' }
	],

	CHOICES_PINP_KEYS: [
		{ id: 21, label: 'PinP & Key 1' },
		{ id: 22, label: 'PinP & Key 2' },
		{ id: 23, label: 'PinP & Key 3' },
		{ id: 24, label: 'PinP & Key 4' }
	],

	CHOICES_PINP_KEYS_INPUTSASSIGN: [
		{ id: 0, label: 'HDMI 1' },
		{ id: 1, label: 'HDMI 2' },
		{ id: 2, label: 'HDMI 3' },
		{ id: 3, label: 'HDMI 4' },
		{ id: 4, label: 'HDMI 5' },
		{ id: 5, label: 'HDMI 6' },
		
		{ id: 6, label: 'SDI 1' },
		{ id: 7, label: 'SDI 2' },
		{ id: 8, label: 'SDI 3' },
		{ id: 9, label: 'SDI 4' },
		{ id: 10, label: 'SDI 5' },
		{ id: 11, label: 'SDI 6' },

		{ id: 12, label: 'Still 1' },
		{ id: 13, label: 'Still 2' },
		{ id: 14, label: 'Still 3' },
		{ id: 15, label: 'Still 4' },
		{ id: 16, label: 'Still 5' },
		{ id: 17, label: 'Still 6' },
		{ id: 18, label: 'Still 7' },
		{ id: 19, label: 'Still 8' },
		{ id: 20, label: 'Still 9' },
		{ id: 21, label: 'Still 10' },
		{ id: 22, label: 'Still 11' },
		{ id: 23, label: 'Still 12' },
		{ id: 24, label: 'Still 13' },
		{ id: 25, label: 'Still 14' },
		{ id: 26, label: 'Still 15' },
		{ id: 27, label: 'Still 16' },

		{ id: 28, label: 'Video Player' },

		{ id: 29, label: 'Input 1' },
		{ id: 30, label: 'Input 2' },
		{ id: 31, label: 'Input 3' },
		{ id: 32, label: 'Input 4' },
		{ id: 33, label: 'Input 5' },
		{ id: 34, label: 'Input 6' },
		{ id: 35, label: 'Input 7' },
		{ id: 36, label: 'Input 8' },
	],

	CHOICES_PINP_TYPES: [
		{ id: 0, label: 'PinP' },
		{ id: 1, label: 'Luminance-White Key' },
		{ id: 2, label: 'Luminance-Black Key' },
		{ id: 3, label: 'Chroma Key' },
	],

	CHOICES_DSK: [
		{ id: 31, label: 'DSK 1' },
		{ id: 32, label: 'DSK 2' }
	],

	CHOICES_DSK_TYPES: [
		{ id: 0, label: 'Luminance-White Key' },
		{ id: 1, label: 'Luminance-Black Key' },
		{ id: 2, label: 'Chroma Key' },
	],

	CHOICES_MEMORY: [
		{ id: 0, label: 'Memory 1' },
		{ id: 1, label: 'Memory 2' },
		{ id: 2, label: 'Memory 3' },
		{ id: 3, label: 'Memory 4' },
		{ id: 4, label: 'Memory 5' },
		{ id: 5, label: 'Memory 6' },
		{ id: 6, label: 'Memory 7' },
		{ id: 7, label: 'Memory 8' },
		{ id: 8, label: 'Memory 9' },
		{ id: 9, label: 'Memory 10' },
		{ id: 10, label: 'Memory 11' },
		{ id: 11, label: 'Memory 12' },
		{ id: 12, label: 'Memory 13' },
		{ id: 13, label: 'Memory 14' },
		{ id: 14, label: 'Memory 15' },
		{ id: 15, label: 'Memory 16' },
		{ id: 16, label: 'Memory 17' },
		{ id: 17, label: 'Memory 18' },
		{ id: 18, label: 'Memory 19' },
		{ id: 19, label: 'Memory 20' },
		{ id: 20, label: 'Memory 21' },
		{ id: 21, label: 'Memory 22' },
		{ id: 22, label: 'Memory 23' },
		{ id: 23, label: 'Memory 24' },
		{ id: 24, label: 'Memory 25' },
		{ id: 25, label: 'Memory 26' },
		{ id: 26, label: 'Memory 27' },
		{ id: 27, label: 'Memory 28' },
		{ id: 28, label: 'Memory 29' },
		{ id: 29, label: 'Memory 30' },
		{ id: 30, label: 'Memory 31' },
		{ id: 31, label: 'Memory 32' }
	],

	CHOICES_CAMERAS: [
		{ id: '51', label: 'Camera 1' },
		{ id: '52', label: 'Camera 2' },
		{ id: '53', label: 'Camera 3' },
		{ id: '54', label: 'Camera 4' },
		{ id: '55', label: 'Camera 5' },
		{ id: '56', label: 'Camera 6' },
		{ id: '57', label: 'Camera 7' },
		{ id: '58', label: 'Camera 8' },
		{ id: '59', label: 'Camera 9' },
		{ id: '5A', label: 'Camera 10' },
		{ id: '5B', label: 'Camera 11' },
		{ id: '5C', label: 'Camera 12' },
	],

	CHOICES_CAMERA_PAN: [
		{ id: '7F', label: 'Left' },
		{ id: '00', label: 'Stop' },
		{ id: '01', label: 'Right' },
	],

	CHOICES_CAMERA_TILT: [
		{ id: '7F', label: 'Down' },
		{ id: '00', label: 'Stop' },
		{ id: '01', label: 'Up' },
	],

	CHOICES_CAMERA_PAN_TILT_SPEED: [
		{ id: '01', label: '1' },
		{ id: '02', label: '2' },
		{ id: '03', label: '3' },
		{ id: '04', label: '4' },
		{ id: '05', label: '5' },
		{ id: '06', label: '6' },
		{ id: '07', label: '7' },
		{ id: '08', label: '8' },
		{ id: '09', label: '9' },
		{ id: '0A', label: '10' },
		{ id: '0B', label: '11' },
		{ id: '0C', label: '12' },
		{ id: '0D', label: '13' },
		{ id: '0E', label: '14' },
		{ id: '0F', label: '15' },
		{ id: '10', label: '16' },
		{ id: '11', label: '17' },
		{ id: '12', label: '18' },
		{ id: '13', label: '19' },
		{ id: '14', label: '20' },
		{ id: '15', label: '21' },
		{ id: '16', label: '22' },
		{ id: '17', label: '23' },
		{ id: '18', label: '24' },
	],

	CHOICES_CAMERA_ZOOM: [
		{ id: '7E', label: 'Wide (Fast)' },
		{ id: '00', label: 'Wide (Slow)' },
		{ id: '01', label: 'Stop' },
		{ id: '02', label: 'Tele (Slow)' },
		{ id: '03', label: 'Tele (Fast)' },
	],

	CHOICES_CAMERA_FOCUS: [
		{ id: '7F', label: 'Near' },
		{ id: '00', label: 'Stop' },
		{ id: '01', label: 'Far' },
	],

	CHOICES_CAMERA_AUTOFOCUS: [
		{ id: '00', label: 'Off' },
		{ id: '01', label: 'On' },
	],

	CHOICES_CAMERA_EXPOSURE: [
		{ id: '00', label: 'Manual' },
		{ id: '01', label: 'Auto' },
	],

	CHOICES_SWITCHES: [
		{ id: '0B0000', label: 'PGM/A 1 SW'},
		{ id: '0B0001', label: 'PGM/A 2 SW'},
		{ id: '0B0002', label: 'PGM/A 3 SW'},
		{ id: '0B0003', label: 'PGM/A 4 SW'},
		{ id: '0B0004', label: 'PGM/A 5 SW'},
		{ id: '0B0005', label: 'PGM/A 6 SW'},
		{ id: '0B0006', label: 'PGM/A 7 SW'},
		{ id: '0B0007', label: 'PGM/A 8 SW'},
		{ id: '0B0008', label: 'PGM/A 9 SW'},
		{ id: '0B0009', label: 'PGM/A 10 SW'},
		{ id: '0B000A', label: 'PST/B 1 SW'},
		{ id: '0B000B', label: 'PST/B 2 SW'},
		{ id: '0B000C', label: 'PST/B 3 SW'},
		{ id: '0B000D', label: 'PST/B 4 SW'},
		{ id: '0B000E', label: 'PST/B 5 SW'},
		{ id: '0B000F', label: 'PST/B 6 SW'},
		{ id: '0B0010', label: 'PST/B 7 SW'},
		{ id: '0B0011', label: 'PST/B 8 SW'},
		{ id: '0B0012', label: 'PST/B 9 SW'},
		{ id: '0B0013', label: 'PST/B 10 SW'},
		{ id: '0B0014', label: 'AUX 1 SW'},
		{ id: '0B0015', label: 'AUX 2 SW'},
		{ id: '0B0016', label: 'AUX 3 SW'},
		{ id: '0B0017', label: 'AUX 4 SW'},
		{ id: '0B0018', label: 'AUX 5 SW'},
		{ id: '0B0019', label: 'AUX 6 SW'},
		{ id: '0B001A', label: 'AUX 7 SW'},
		{ id: '0B001B', label: 'AUX 8 SW'},
		{ id: '0B001C', label: 'AUX 9 SW'},
		{ id: '0B001D', label: 'AUX 10 SW'},
		{ id: '0B001E', label: 'CUT SW'},
		{ id: '0B001F', label: 'AUTO SW'},
		{ id: '0B0020', label: 'TRANSITION SW'},
		{ id: '0B0021', label: 'MODE SW'},
		{ id: '0B0022', label: 'INPUT ASSIGN SW'},
		{ id: '0B0023', label: 'PGM-CENTER ENCODER'},
		{ id: '0B0024', label: 'PST-CENTER ENCODER'},
		{ id: '0B0025', label: 'SPLIT A SW'},
		{ id: '0B0026', label: 'SPLIT B SW'},
		{ id: '0B0027', label: 'AUTO MIXING'},
		{ id: '0B0028', label: 'CAPTURE SW'},
		{ id: '0B0029', label: 'USER 1 SW'},
		{ id: '0B002A', label: 'USER 2 SW'},
		{ id: '0B002B', label: 'USER 3 SW'},
		{ id: '0B002C', label: 'USER 4 SW'},
		{ id: '0B002D', label: 'PinP 1 POSITION H'},
		{ id: '0B002E', label: 'PinP 1 POSITION V'},
		{ id: '0B002F', label: 'PinP 1 SOURCE SW'},
		{ id: '0B0030', label: 'PinP 1 PVW SW'},
		{ id: '0B0031', label: 'PinP 1 PGM SW'},
		{ id: '0B0032', label: 'PinP 2 POSITION H'},
		{ id: '0B0033', label: 'PinP 2 POSITION V'},
		{ id: '0B0034', label: 'PinP 2 SOURCE SW'},
		{ id: '0B0035', label: 'PinP 2 PVW SW'},
		{ id: '0B0036', label: 'PinP 2 PGM SW'},
		{ id: '0B0037', label: 'PinP 3 POSITION H'},
		{ id: '0B0038', label: 'PinP 3 POSITION V'},
		{ id: '0B0039', label: 'PinP 3 SOURCE SW'},
		{ id: '0B003A', label: 'PinP 3 PVW SW'},
		{ id: '0B003B', label: 'PinP 3 PGM SW'},
		{ id: '0B003C', label: 'PinP 4 POSITION H'},
		{ id: '0B003D', label: 'PinP 4 POSITION V'},
		{ id: '0B003E', label: 'PinP 4 SOURCE SW'},
		{ id: '0B003F', label: 'PinP 4 PVW SW'},
		{ id: '0B0040', label: 'PinP 4 PGM SW'},
		{ id: '0B0041', label: 'DSK 1 SOURCE SW'},
		{ id: '0B0042', label: 'DSK 1 PVW SW'},
		{ id: '0B0043', label: 'DSK 1 PGM SW'},
		{ id: '0B0044', label: 'DSK 2 SOURCE SW'},
		{ id: '0B0045', label: 'DSK 2 PVW SW'},
		{ id: '0B0046', label: 'DSK 2 PGM SW'},
		{ id: '0B0047', label: 'MONITOR 1 SW'},
		{ id: '0B0048', label: 'MONITOR 2 SW'},
		{ id: '0B0049', label: 'MONITOR 3 SW'},
		{ id: '0B004A', label: 'MONITOR 4 SW'},
		{ id: '0B004B', label: 'MENU SW'},
		{ id: '0B004C', label: 'EXIT SW'},
		{ id: '0B004D', label: 'ENTER SW'},
		{ id: '0B004E', label: 'OUTPUT FADE SW'},
		{ id: '0B004F', label: 'SEQUENCER ON SW'},
		{ id: '0B0050', label: 'SEQUENCER AUTO SW'},
		{ id: '0B0051', label: 'SEQUENCER PREV SW'},
		{ id: '0B0052', label: 'SEQUENCER NEXT SW'},
	]
}